# Generated by Django 4.2.13 on 2024-07-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
